# timeout
timeout = "1200s"
# your website url
baseURL = 'https://dkinsman.github.io'
# website title
title = 'Dawson Kinsman'
# don't touch this
disableKinds = ["section", "taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true
defaultContentLanguage = 'en'

# theme as module
[module]
[[module.imports]]
path = "bridget" # deploy with git (recommended)  WARN: you should also set `bundled` to true in params.toml !!!

[caches]
  [caches.images]
    dir = ':cacheDir/images'