# timeout
timeout = "1200s"
# your website url
baseURL = 'https://dkinsman.github.io'
# website title
title = 'Dawson Kinsman'
# don't touch this
disableKinds = ["section", "taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true
defaultContentLanguage = 'en'

# theme as module
[module]
replacements = "github.com/Sped0n/bridget/v2 -> bridget" # deploy with local dir (relative to hugo site theme dir)  WARN: delete this line if you want to deploy with git
[[module.imports]]
path = "github.com/Sped0n/bridget/v2" # deploy with git (recommended)  WARN: you should also set `bundled` to true in params.toml !!!

[caches]
  [caches.images]
    dir = ':cacheDir/images'